### ISSUE TITLE
Exometer fails to compile in Elixir 1.1

### ISSUE THREAD

**Issue by scohen** [Feuerlabs/exometer#138] opened 2015-12-04 18:14 UTC
It's due to exometer_core requiring a file in another project; See the discussion here: 
https://github.com/elixir-lang/elixir/issues/4044

BTW, we really like exometer; it powers all of our Elixir metrics. Thanks for your work!

**Comment by tolbrino** [comment] 2015-12-05 12:22
@uwiger Consider this a pat on the back :-)

@scohen Could you try tag 1.2.1 and report back?

**Comment by tehprofessor** [comment] 2015-12-21 19:33
Howdy y'all,

I was wondering if someone could point me at a fix for this? Or if there is an expected time frame for one? I'm unfortunately going to have to rip Exometer out of a project as I can no longer get it to build on Linux using Elixir and it's holding up deployment of our application.

I'd also be willing to lend a hand (or commit) to to get this fixed if someone can point me in the right direction.

**Comment by scohen** [comment] 2015-12-21 19:49
@tolbrino it still fails with:

```
ERROR: compile failed while processing /Users/steve/Projects/elixometer/deps/exometer_collectd: rebar_abort
** (Mix) Could not compile dependency :exometer_collectd, "/usr/local/bin/rebar" command failed. You can recompile this dependency with "mix deps.compile exometer_collectd", update it with "mix deps.update exometer_collectd" or clean it with "mix deps.clean exometer_collectd"
```

**Comment by scohen** [comment] 2015-12-21 19:51
@tehprofessor There's a [fork of exometer](
https://github.com/pspdfkit-labs/exometer) that works for us. Don't abandon exometer, it's awesome.

**Comment by tehprofessor** [comment] 2015-12-21 20:02
@scohen I don't want to, it definitely rocks :smile: but... taht fork doesn't work for me either when I build on Debian Jessie. I've tried several versions of Elixir going back to 1.0.4.

I get an error nearly identical to the one you posted above a few minutes ago.

**Comment by uwiger** [comment] 2015-12-21 20:09
Have you tried just using exometer_core instead?

**Comment by tehprofessor** [comment] 2015-12-21 20:30
First off, thanks for the quick replies and help-- y'all rock!

@uwiger Do you mean only including it (`exometer_core`) as a dependency instead of just `exometer`? If so, yes, I just tried it but it produces the following error when I try to compile using this repo's exometer:

```bash
Unchecked dependencies for environment dev:
* meck (git://github.com/eproxus/meck.git)
  the dependency meck in deps/exometer_core/rebar.config is overriding a child dependency:

  > In deps/exometer_core/rebar.config:
    {:meck, ~r/.*/, [git: "git://github.com/eproxus/meck.git", tag: "0.8.2"]}

  > In deps/folsom/rebar.config:
    {:meck, ~r/.*/, [git: "git://github.com/eproxus/meck", tag: "0.8.2"]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

If I use the `pspdfkit` fork of `exometer_core`, after compiling I get this error:

```
=INFO REPORT==== 21-Dec-2015::12:27:59 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application exometer: could not find application file: exometer.app
```

**Comment by uwiger** [comment] 2015-12-21 20:38
So the only difference between the two deps entries is the ".git" suffix?
That ought to be fixable.

The second error is due to trying to start exometer instead of exometer_core.

Note: exometer requires exometer_core. The main difference is that exometer_core has much fewer dependencies; it implements the core metric types as well as the exometer_report framework.

The main reason for using exometer would be if you require one or more of the reporters contained there.

**Comment by tehprofessor** [comment] 2015-12-21 20:45
Hell yes! @uwiger Switching to start up `exometer_core` works wonderfully and I can compile! 

:confetti_ball:  :tada: 

Thank you guys so damn much for you help.

**Comment by scohen** [comment] 2015-12-21 21:20
@uwiger `exometer_core` also compiles, though I do need the graphite and opentsdb reporters that reside in exometer.

**Comment by uwiger** [comment] 2015-12-21 21:52
So I don't know how Mix works, but the (admittedly somewhat unusual) way to "prune" exometer's deps is to instruct `rebar.config.script` (which is automatically evaluated by rebar) using the OS environment variable EXOMETER_PACKAGES, e.g. `EXOMETER_PACKAGES=basic`. This will dynamically reduce the dependency list.

The graphite and opentsdb reporters don't need any of the deps, except for what exometer_core requires.

**Comment by scohen** [comment] 2015-12-21 22:34
I'll experiment further; it should be relatively easy to set an environment variable in mix.

**Comment by tolbrino** [comment] 2015-12-22 10:20
@scohen Hmm, for some reason I can't reproduce the error anymore. Did you try to remove the `deps` directory such that all exometer-related dependencies are fetched with the right version again?

**Comment by scohen** [comment] 2015-12-22 18:13
@tolbrino: Yep, I just removed the deps directory and unlocked and updated exometer and exometer_core. I got the same error. I'm compiling under 1.1.1 on MacOS, though it fails the same way under 1.1 on linux.

**Comment by linearregression** [comment] 2016-01-14 01:57
@ scohen  unsure if you still have issue.
May be you can alias rebar to rebar -vvv (?please check), to get rebar to run in  verbose mode. Get the more detailed logs to troubleshoot and/or posted it here.
Looks like you have rebar 2.0. 3.0is called rebar3 in executable.

**Comment by scohen** [comment] 2016-01-14 23:49
It's still there, here's the output:

**Comment by linearregression** [comment] 2016-01-15 06:32
I assume it is related to elixometer project?
- retry with "mix deps.compile setup", update it with "mix deps.update setup" or clean it with "mix deps.clean setup"?
- Can you backup your work and start clean from git clone?
I used forked repo of your elixometer and did a carpet build on travis.
https://travis-ci.org/linearregression/elixometer/builds/102530185

It looks like it passes most ...

**Comment by scohen** [comment] 2016-01-15 16:59
Did you re-add exometer as a dep to elixometer? If you forked the repo recently, I removed exometer. Also, elixometer uses pspdfkit-labs's fork of exometer/exometer_core, which compiles under elixir.

**Comment by linearregression** [comment] 2016-01-15 20:11
No I did not manually add to elixomeer. The most recent test use feubarlab's. Looks like it compiles but tests fail for other reasons.
https://travis-ci.org/linearregression/elixometer/builds/102678199

**Comment by tolbrino** [comment] 2016-01-19 13:19
@scohen Could you verify that #143 compiles for you as well? I tested it with Elixir 1.2.

**Comment by tolbrino** [comment] 2016-01-28 10:24
Looks like the merged change fixed this issue. In case it still persists, feel free to re-open.

**Closed by tolbrino** 2016-01-28 10:24 UTC
Labels: bug

**Comment by scohen** [comment] 2016-01-28 17:04
Thanks!

**Comment by vicky-fd** [comment] 2016-08-01 10:39
My Config.exs config for exometer is :
config(:elixometer, reporter: :exometer_report_tty,
            env: Mix.env,
            metric_prefix: "reverse_proxy") **_where reverse proxy is my application name_**

Mix.exs file config is as follows:
def application do
[applications: [:exometer,...]]
end

defp deps do
...
{:exometer_core, github: "PSPDFKit-labs/exometer_core", override: true},
     {:exometer, github: "PSPDFKit-labs/exometer"},
     {:edown, github: "uwiger/edown", tag: "0.7", override: true},
...
end

Exception I am getting while running "iex -S mix" is as follows:
Unchecked dependencies for environment dev:
- exometer (https://github.com/PSPDFKit-labs/exometer.git)
  could not find an app file at _build/dev/lib/exometer/ebin/exometer.app. This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
  *\* (Mix) Can't continue due to errors on dependencies

Please help.

**Comment by tolbrino** [comment] 2016-08-15 07:40
@vicky-fd This sounds like an issue of elixometer which uses the exometer fork from PSPDFKit-Labs. Maybe they've got a more recent version which fixes your issue.
